package.json
server/index.js
server/models.js

axios get request

---

Client/SRC/App.jsx
Client/SRC/Components/RatingsNReviews/RatingsNReviews.jsx
server/index.js

syntax error fix, command "npm start" now renders page on localhost/3000

syntax error fix running npm start can render page on localhost/3000

---

Client/SRC/Components/RatingsNReviews/Ratings.jsx
Client/SRC/Components/RatingsNReviews/RatingsNReviews.jsx
Client/SRC/Components/RatingsNReviews/Reviews.jsx
package-lock.json

hardcoded outline for components

---

Client/SRC/Components/RatingsNReviews/RatingsNReviews.Test.js
Test/test.js
package-lock.json

added test files for R n R

---

Client/SRC/App.jsx
Client/SRC/Components/RatingsNReviews/Ratings.jsx
Client/SRC/Components/RatingsNReviews/RatingsNReviews.Test.js
Client/SRC/Components/RatingsNReviews/RatingsNReviews.jsx
Client/SRC/Components/RatingsNReviews/ReviewCard.jsx
Client/SRC/Components/RatingsNReviews/Reviews.jsx
package-lock.json
package.json

rendering api data in ratings and reviews, updated get requests in r n r main

rendering api data using get requests in R n R main

---

Client/SRC/Components/DKProdComp/AddToOutfitsCard.jsx
Client/SRC/Components/DKProdComp/Card.jsx
Client/SRC/Components/DKProdComp/RIAC.jsx

- fixed bug where outfits could scroll indefinitely

fixed scroll functionality for outfits

---

Client/SRC/Components/DKProdComp/AddToOutfitsCard.jsx
Client/SRC/Components/DKProdComp/Card.jsx
Client/SRC/Components/DKProdComp/RIAC.jsx

- able to add and remove recommended items from outfits
- able add current outfit to outfits list

Carousel Adding Outfits functionality

---

Client/SRC/Components/DOverview/ImageBuilder.jsx
Client/SRC/Components/DOverview/MiniImageBuilder.jsx
Client/SRC/Components/DOverview/Overview.jsx
Client/SRC/Components/DOverview/RandNBuilder.jsx
Client/SRC/Components/DOverview/StyleSelector.jsx
Client/SRC/Components/DOverview/StyleSelectorBuilder.jsx

-Added state tracking to overview to manage sub components
-added click events to change between style types and update other components
-added click events to change through the image gallery based on the selected style

Added dynamic image changes

---

Client/SRC/App.jsx
Client/SRC/Components/YQandA/QAMain.jsx
Client/SRC/Components/YQandA/Refactoring/Answer.jsx
Client/SRC/Components/YQandA/Search.jsx
Client/SRC/Components/YQandA/styles/Helpful.style.js
server/index.js
server/models.js

Made GET request successfully for QA and also rendered the question list to the DOM

GET request for QA and question list rendering from DB

---

Client/SRC/App.jsx
Client/SRC/Components/DKProdComp/Card.jsx
Client/SRC/Components/DKProdComp/LeftArrow.jsx
Client/SRC/Components/DKProdComp/RIAC.jsx
Client/SRC/Components/DKProdComp/RightArrow.jsx

- modularized arrows into components
- pulls and uses data from the api
- may need either reorganizing routes to make fewer requests at once

Uses data from api

---

Client/SRC/App.jsx
Client/SRC/Components/DOverview/ImageBuilder.jsx
Client/SRC/Components/DOverview/Overview.jsx
Client/SRC/Navbar.jsx
server/index.js
server/models.js

-Created and styled the Navbar for the App
-Added a click tracker function that can be passed and used within components
-Click tracker still needs some logic work to grab the right data to post to server
-Set up functioning click tracker routes and data structure

Implemented click tracker and nav bar

---

Client/SRC/Components/RatingsNReviews/ratings/RatingsSlider.jsx

fixed bug where clicking different items breaks page

fixed bug where clicking different items breaks page

---

Client/SRC/Components/YQandA/Refactoring/QuestionModal.jsx
Client/SRC/Components/YQandA/Refactoring/QuestionSearch.jsx
Client/SRC/Components/YQandA/test/QA.test.js

Test for displaying Search implemented.

New test added

---

Client/SRC/Components/RatingsNReviews/RatingsNReviews.jsx
Client/SRC/Components/RatingsNReviews/ratings/Ratings.jsx
Client/SRC/Components/RatingsNReviews/reviews/Reviews.jsx

style guide update on components, star ratings bug fix

style syntax

---

Client/DIST/styles.css
Client/SRC/Components/DOverview/CartBuilder.jsx
Client/SRC/Components/DOverview/Checkbox.jsx
Client/SRC/Components/DOverview/ImageBuilder.jsx
Client/SRC/Components/DOverview/MiniImageBuilder.jsx
Client/SRC/Components/DOverview/Overview.jsx
Client/SRC/Components/DOverview/ProductInfo.jsx
Client/SRC/Components/DOverview/SelectQuantity.jsx
Client/SRC/Components/DOverview/SelectSize.jsx
Client/SRC/Components/DOverview/StyleSelector.jsx
Client/SRC/Components/DOverview/StyleSelectorBuilder.jsx
Client/SRC/Navbar.jsx

-updated checkbox to a class component
-added component mount and update functionality to track and modify dynamic display of a checkmark
-integrated tracking logic to use already established click events to modify state and update display
-Updated CSS across multiple components within overview and the navbar to stabilize sizing issues
-still need to convert select boxes from styled components to have shared styling across the app
(will still maintain some local inline styling for display purposes)

Implemented checkbox display for selected style, updated CSS

---

Client/SRC/Components/RatingsNReviews/ratings/Ratings.jsx
Client/SRC/Components/RatingsNReviews/reviews/ReviewCard.jsx

star rating upgraded

---

Client/SRC/Components/RatingsNReviews/ratings/Ratings.jsx
Client/SRC/Components/RatingsNReviews/ratings/RatingsSlider.jsx

syntax changes

---

Client/SRC/Components/RatingsNReviews/ratings/Ratings.jsx
Client/SRC/Components/RatingsNReviews/reviews/Reviews.jsx

style conformity

---

Client/SRC/Components/RatingsNReviews/ratings/Ratings.jsx
Client/SRC/Components/RatingsNReviews/reviews/ReviewCard.jsx
expressconfig.ex.js
expressconfig.example.js

more css styling and some config fixes

more css styling and some config fixes

---

Client/SRC/Components/RatingsNReviews/ratings/Ratings.jsx

more css styling and some config fixes

css changes

---

Client/SRC/Components/RatingsNReviews/ratings/BarGraph/BarGraph.jsx

fixed issue #96 unused classnames

fixed issue #96 unused classnames
